# Generated by Django 2.2.24 on 2021-08-10 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0005_auto_20210810_1517'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopuser',
            name='age',
            field=models.PositiveIntegerField(blank=True, default=0, verbose_name='возраст'),
        ),
    ]
